# Generated by Django 4.0.1 on 2022-01-07 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True, verbose_name='Category_name')),
                ('gender', models.CharField(max_length=50, verbose_name='For Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=100, unique=True, verbose_name='Language name')),
                ('greetings', models.TextField(blank=True, verbose_name='Greeting message')),
                ('name_ask', models.TextField(blank=True, verbose_name='Asking for a name')),
                ('phone_ask', models.TextField(blank=True, verbose_name='Asking for a phone')),
                ('menu', models.TextField(blank=True, verbose_name='Menu message')),
                ('category_menu', models.TextField(blank=True, verbose_name='Category button in the menu')),
                ('question_menu', models.TextField(blank=True, verbose_name='"Ask a question" button ')),
                ('chat_menu', models.TextField(blank=True, verbose_name='"Group-chat menu" button ')),
                ('info_menu', models.TextField(blank=True, verbose_name='"Information about us" button')),
                ('info', models.TextField(blank=True, verbose_name='Information')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=100, unique=True, verbose_name='User`s TG id')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='User`s name')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='User`s phone')),
                ('chosen_category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='bot.category')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.language')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(verbose_name='Publication`s topic')),
                ('text', models.TextField(verbose_name='Pulication`s text')),
                ('link', models.CharField(blank=True, max_length=100, verbose_name='Reference link')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.category')),
            ],
        ),
    ]
