# Generated by Django 4.0.1 on 2022-01-08 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_user_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='language_name',
            new_name='name',
        ),
    ]
