# Generated by Django 4.0.1 on 2022-01-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_language_send_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='language_set',
            field=models.TextField(blank=True, verbose_name='Particular language has been chosen'),
        ),
    ]
