# Generated by Django 4.0.1 on 2022-01-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_language_language_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='successful_registration',
            field=models.TextField(blank=True, verbose_name='Successful registatration'),
        ),
    ]
