# Generated by Django 4.0.1 on 2022-01-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_language_successful_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='back',
            field=models.TextField(blank=True, verbose_name='Back button'),
        ),
    ]
