# Generated by Django 4.0.1 on 2022-01-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_language_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='chat',
            field=models.TextField(blank=True, verbose_name='Link to chat'),
        ),
    ]
