# Generated by Django 4.0.1 on 2022-01-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_language_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='language_selection',
            field=models.TextField(blank=True, verbose_name='Select a language'),
        ),
    ]
