# Generated by Django 4.0.1 on 2022-01-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_language_used_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='used_link',
        ),
    ]
