# Generated by Django 4.0.1 on 2022-01-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_remove_language_used_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='User telegram ID')),
                ('text', models.TextField(verbose_name='Text of the question')),
                ('status', models.BooleanField(default=False, verbose_name='Is question answered ?')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Answer to the question')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Asked at:')),
            ],
        ),
        migrations.AddField(
            model_name='language',
            name='ask_question',
            field=models.TextField(blank=True, verbose_name='Ask a anonimus question'),
        ),
        migrations.AddField(
            model_name='user',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name='User`s question'),
        ),
    ]
