# Generated by Django 4.0.1 on 2022-01-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_question_language_ask_question_user_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='check_question',
            field=models.TextField(blank=True, verbose_name='Chek if question is correct'),
        ),
        migrations.AddField(
            model_name='language',
            name='no',
            field=models.TextField(blank=True, verbose_name='No'),
        ),
        migrations.AddField(
            model_name='language',
            name='yes',
            field=models.TextField(blank=True, verbose_name='Yes'),
        ),
    ]
