# Generated by Django 4.0.1 on 2022-01-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_language_check_question_language_no_language_yes'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='answer',
            field=models.TextField(blank=True, verbose_name='Answer to the question'),
        ),
        migrations.AddField(
            model_name='language',
            name='answered_question',
            field=models.TextField(blank=True, verbose_name='Your question have been answered'),
        ),
        migrations.AddField(
            model_name='language',
            name='question',
            field=models.TextField(blank=True, verbose_name='User`s question'),
        ),
    ]
