# Generated by Django 4.0.1 on 2022-01-10 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_language_question_creater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='question_creater',
            new_name='question_created',
        ),
    ]
