# Generated by Django 4.0.1 on 2022-01-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_rename_question_creater_language_question_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='categories',
            field=models.TextField(blank=True, verbose_name='Choose category'),
        ),
    ]
