# Generated by Django 4.0.1 on 2022-01-10 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_language_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='key_words',
            field=models.TextField(blank=True, verbose_name='Write keyword in order t find ublication'),
        ),
        migrations.AddField(
            model_name='publication',
            name='langauge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bot.language'),
            preserve_default=False,
        ),
    ]
