# Generated by Django 4.0.1 on 2022-01-11 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_language_key_words_publication_langauge'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(verbose_name='Keyword')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.publication')),
            ],
        ),
    ]
