# Generated by Django 4.0.1 on 2022-01-11 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_keyword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='langauge',
            new_name='language',
        ),
    ]
