# Generated by Django 4.0.1 on 2022-01-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_rename_langauge_publication_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='posts_found',
            field=models.TextField(blank=True, verbose_name='There are posts on your request'),
        ),
        migrations.AddField(
            model_name='language',
            name='reference_link',
            field=models.TextField(blank=True, verbose_name='Link to the resource'),
        ),
    ]
