# Generated by Django 4.0.1 on 2022-01-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_language_no_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of link')),
                ('link', models.CharField(max_length=100, verbose_name='Link itself')),
            ],
        ),
    ]
