# Generated by Django 4.0.1 on 2022-01-12 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_links'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
    ]
