# Generated by Django 4.0.1 on 2022-01-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0026_language_numbers_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='incorrect_phone',
            field=models.TextField(blank=True, verbose_name='Phone was inputed inproperly!'),
        ),
    ]
