# Generated by Django 4.0.1 on 2022-01-12 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0027_language_incorrect_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='bot.category'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='language',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='bot.language'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='text',
            field=models.TextField(blank=True, verbose_name='Pulication`s text'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='topic',
            field=models.TextField(blank=True, verbose_name='Publication`s topic'),
        ),
    ]
