# Generated by Django 4.0.1 on 2022-01-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0029_alter_publication_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference link'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='topic',
            field=models.TextField(blank=True, null=True, verbose_name='Publication`s topic'),
        ),
    ]
