# Generated by Django 4.0.1 on 2022-01-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0030_alter_publication_link_alter_publication_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='gender',
        ),
        migrations.AddField(
            model_name='language',
            name='video',
            field=models.TextField(blank=True, verbose_name='Video-instruction'),
        ),
    ]
