# Generated by Django 4.0.1 on 2022-01-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0031_remove_category_gender_language_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='video_text',
            field=models.TextField(blank=True, verbose_name='Here is the link to the video'),
        ),
    ]
