# Generated by Django 4.0.1 on 2022-01-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0034_alter_link_category_alter_publication_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Language code'),
        ),
    ]
