# Generated by Django 4.0.1 on 2022-01-13 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0035_language_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name of the questionnaire')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.category')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text of the question')),
                ('text_ru', models.TextField(null=True, verbose_name='Text of the question')),
                ('text_uz', models.TextField(null=True, verbose_name='Text of the question')),
                ('questionnaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text of the answer')),
                ('text_ru', models.TextField(null=True, verbose_name='Text of the answer')),
                ('text_uz', models.TextField(null=True, verbose_name='Text of the answer')),
                ('correct', models.BooleanField(default=False, verbose_name='Correct of not')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.questionpoll')),
                ('questionnaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.questionnaire')),
            ],
        ),
    ]
