# Generated by Django 4.0.1 on 2022-01-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0036_questionnaire_questionpoll_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='no_polls',
            field=models.TextField(blank=True, verbose_name='There are no polls'),
        ),
        migrations.AddField(
            model_name='language',
            name='poll_button',
            field=models.TextField(blank=True, verbose_name='"Select poll" buton'),
        ),
        migrations.AddField(
            model_name='language',
            name='select_poll',
            field=models.TextField(blank=True, verbose_name='Select poll'),
        ),
    ]
