# Generated by Django 4.0.1 on 2022-01-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0037_language_no_polls_language_poll_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='selected_category',
            field=models.TextField(blank=True, verbose_name='Menu for category'),
        ),
    ]
