# Generated by Django 4.0.1 on 2022-01-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0038_language_selected_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='find',
            field=models.TextField(blank=True, verbose_name='Find posts'),
        ),
    ]
