# Generated by Django 4.0.1 on 2022-01-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0039_language_find'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='correct',
        ),
        migrations.AddField(
            model_name='answer',
            name='points',
            field=models.IntegerField(null=True, verbose_name='Number of points for answer'),
        ),
        migrations.AlterField(
            model_name='language',
            name='key_words',
            field=models.TextField(blank=True, verbose_name='Write keyword in order to find publication'),
        ),
    ]
