# Generated by Django 4.0.1 on 2022-01-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0040_remove_answer_correct_answer_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='answers',
            field=models.TextField(default=1, verbose_name='Table with answer-points'),
            preserve_default=False,
        ),
    ]
