# Generated by Django 4.0.1 on 2022-01-13 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0041_questionnaire_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.questionnaire'),
        ),
    ]
