# Generated by Django 4.0.1 on 2022-01-13 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0042_user_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.questionpoll'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.questionnaire'),
        ),
        migrations.AlterField(
            model_name='questionpoll',
            name='questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.questionnaire'),
        ),
    ]
