# Generated by Django 4.0.1 on 2022-01-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0043_alter_answer_question_alter_answer_questionnaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.TextField(unique=True, verbose_name='Name of the questionnaire'),
        ),
    ]
