# Generated by Django 4.0.1 on 2022-01-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0045_language_points_language_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='poll_selected',
            field=models.TextField(blank=True, verbose_name='Questionnaire have been selected'),
        ),
    ]
