# Generated by Django 4.0.1 on 2022-01-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0046_language_poll_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='back_category',
            field=models.TextField(blank=True, verbose_name='Back to categories'),
        ),
    ]
