# Generated by Django 4.0.1 on 2022-01-14 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0047_language_back_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='anonymous',
            field=models.TextField(blank=True, verbose_name='"Stay Anonymous" button'),
        ),
        migrations.AddField(
            model_name='language',
            name='skip',
            field=models.TextField(blank=True, verbose_name='"Skip" button'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='bot.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='language',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='bot.language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.CharField(default=9, max_length=100, verbose_name='Reference link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='topic',
            field=models.TextField(default=9, verbose_name='Publication`s topic'),
            preserve_default=False,
        ),
    ]
