# Generated by Django 4.0.1 on 2022-01-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0048_language_anonymous_language_skip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='Is user anonymous?'),
        ),
    ]
