# Generated by Django 4.0.1 on 2022-01-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0049_user_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=256, verbose_name='Text of the answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Text of the answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Text of the answer'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Name of the questionnaire'),
        ),
    ]
