# Generated by Django 4.0.1 on 2022-01-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0052_alter_publication_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text of suggestion')),
                ('user_id', models.CharField(max_length=100, verbose_name='Telegram if of the user')),
            ],
        ),
        migrations.AddField(
            model_name='language',
            name='suggestion',
            field=models.TextField(blank=True, verbose_name='"Add suggestion" button'),
        ),
        migrations.AddField(
            model_name='language',
            name='thanks_suggestion',
            field=models.TextField(blank=True, verbose_name='Thanks for suggestion!'),
        ),
    ]
