# Generated by Django 4.0.1 on 2022-01-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0054_rename_suggestions_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='write_suggestion',
            field=models.TextField(blank=True, verbose_name='Write your suggestion'),
        ),
    ]
