# Generated by Django 4.0.1 on 2022-01-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0055_language_write_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(max_length=256, verbose_name='Text of the answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_ru',
            field=models.TextField(max_length=256, null=True, verbose_name='Text of the answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_uz',
            field=models.TextField(max_length=256, null=True, verbose_name='Text of the answer'),
        ),
    ]
