# Generated by Django 4.0.1 on 2022-01-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0056_alter_answer_text_alter_answer_text_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=256, verbose_name='Text of the answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Text of the answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Text of the answer'),
        ),
    ]
