# Generated by Django 4.0.1 on 2022-01-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0058_questionnaire_name_ru_questionnaire_name_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='answers_ru',
            field=models.TextField(null=True, verbose_name='Table with answer-points'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='answers_uz',
            field=models.TextField(null=True, verbose_name='Table with answer-points'),
        ),
    ]
