# Generated by Django 4.0.1 on 2022-01-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0059_questionnaire_answers_ru_questionnaire_answers_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Age of user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='gender',
            field=models.CharField(blank=True, max_length=100, verbose_name='User`s gender'),
        ),
        migrations.AddField(
            model_name='language',
            name='height',
            field=models.CharField(blank=True, max_length=100, verbose_name='User`s height,'),
        ),
        migrations.AddField(
            model_name='language',
            name='mariage',
            field=models.CharField(blank=True, max_length=100, verbose_name='Is user married?'),
        ),
        migrations.AddField(
            model_name='language',
            name='weight',
            field=models.CharField(blank=True, max_length=100, verbose_name='User`s weight'),
        ),
        migrations.AlterField(
            model_name='language',
            name='skip',
            field=models.CharField(blank=True, max_length=100, verbose_name='"Skip" button'),
        ),
    ]
