# Generated by Django 4.0.1 on 2022-01-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0061_alter_language_age_alter_language_anonymous_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='age',
            field=models.CharField(blank=True, max_length=256, verbose_name='Age of user'),
        ),
        migrations.AlterField(
            model_name='language',
            name='anonymous',
            field=models.CharField(blank=True, max_length=256, verbose_name='"Stay Anonymous" button'),
        ),
        migrations.AlterField(
            model_name='language',
            name='answer',
            field=models.CharField(blank=True, max_length=256, verbose_name='Answer to the question'),
        ),
        migrations.AlterField(
            model_name='language',
            name='answered_question',
            field=models.CharField(blank=True, max_length=256, verbose_name='Your question have been answered'),
        ),
        migrations.AlterField(
            model_name='language',
            name='ask_question',
            field=models.CharField(blank=True, max_length=256, verbose_name='Ask a anonimus question'),
        ),
        migrations.AlterField(
            model_name='language',
            name='back',
            field=models.CharField(blank=True, max_length=256, verbose_name='Back button'),
        ),
        migrations.AlterField(
            model_name='language',
            name='back_category',
            field=models.CharField(blank=True, max_length=256, verbose_name='Back to categories'),
        ),
        migrations.AlterField(
            model_name='language',
            name='categories',
            field=models.CharField(blank=True, max_length=256, verbose_name='Choose category'),
        ),
        migrations.AlterField(
            model_name='language',
            name='category_menu',
            field=models.CharField(blank=True, max_length=256, verbose_name='Category button in the menu'),
        ),
        migrations.AlterField(
            model_name='language',
            name='chat',
            field=models.CharField(blank=True, max_length=256, verbose_name='Link to chat'),
        ),
        migrations.AlterField(
            model_name='language',
            name='chat_menu',
            field=models.CharField(blank=True, max_length=256, verbose_name='"Group-chat menu" button '),
        ),
        migrations.AlterField(
            model_name='language',
            name='check_question',
            field=models.CharField(blank=True, max_length=256, verbose_name='Chek if question is correct'),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(blank=True, max_length=256, verbose_name='Language code'),
        ),
        migrations.AlterField(
            model_name='language',
            name='find',
            field=models.CharField(blank=True, max_length=256, verbose_name='Find posts'),
        ),
        migrations.AlterField(
            model_name='language',
            name='gender',
            field=models.CharField(blank=True, max_length=256, verbose_name='User`s gender'),
        ),
        migrations.AlterField(
            model_name='language',
            name='greetings',
            field=models.CharField(blank=True, max_length=256, verbose_name='Greeting message'),
        ),
        migrations.AlterField(
            model_name='language',
            name='height',
            field=models.CharField(blank=True, max_length=256, verbose_name='User`s height,'),
        ),
        migrations.AlterField(
            model_name='language',
            name='incorrect_phone',
            field=models.CharField(blank=True, max_length=256, verbose_name='Phone was inputed inproperly!'),
        ),
        migrations.AlterField(
            model_name='language',
            name='info',
            field=models.CharField(blank=True, max_length=256, verbose_name='Information'),
        ),
        migrations.AlterField(
            model_name='language',
            name='info_menu',
            field=models.CharField(blank=True, max_length=256, verbose_name='"Information about us" button'),
        ),
        migrations.AlterField(
            model_name='language',
            name='key_words',
            field=models.CharField(blank=True, max_length=256, verbose_name='Write keyword in order to find publication'),
        ),
        migrations.AlterField(
            model_name='language',
            name='language_selection',
            field=models.CharField(blank=True, max_length=256, verbose_name='Select a language'),
        ),
        migrations.AlterField(
            model_name='language',
            name='language_set',
            field=models.CharField(blank=True, max_length=256, verbose_name='Particular language has been chosen'),
        ),
        migrations.AlterField(
            model_name='language',
            name='marriage',
            field=models.CharField(blank=True, max_length=256, verbose_name='Is user married?'),
        ),
        migrations.AlterField(
            model_name='language',
            name='menu',
            field=models.CharField(blank=True, max_length=256, verbose_name='Menu message'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Language name'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name_ask',
            field=models.CharField(blank=True, max_length=256, verbose_name='Asking for a name'),
        ),
        migrations.AlterField(
            model_name='language',
            name='no',
            field=models.CharField(blank=True, max_length=256, verbose_name='No'),
        ),
        migrations.AlterField(
            model_name='language',
            name='no_polls',
            field=models.CharField(blank=True, max_length=256, verbose_name='There are no polls'),
        ),
        migrations.AlterField(
            model_name='language',
            name='no_posts',
            field=models.CharField(blank=True, max_length=256, verbose_name='There are no posts'),
        ),
        migrations.AlterField(
            model_name='language',
            name='numbers_name',
            field=models.CharField(blank=True, max_length=256, verbose_name='There are numbers in name'),
        ),
        migrations.AlterField(
            model_name='language',
            name='phone_ask',
            field=models.CharField(blank=True, max_length=256, verbose_name='Asking for a phone'),
        ),
        migrations.AlterField(
            model_name='language',
            name='points',
            field=models.CharField(blank=True, max_length=256, verbose_name='Points for answer'),
        ),
        migrations.AlterField(
            model_name='language',
            name='poll_button',
            field=models.CharField(blank=True, max_length=256, verbose_name='"Select poll" buton'),
        ),
        migrations.AlterField(
            model_name='language',
            name='poll_selected',
            field=models.CharField(blank=True, max_length=256, verbose_name='Questionnaire have been selected'),
        ),
        migrations.AlterField(
            model_name='language',
            name='posts_found',
            field=models.CharField(blank=True, max_length=256, verbose_name='There are posts on your request'),
        ),
        migrations.AlterField(
            model_name='language',
            name='question',
            field=models.CharField(blank=True, max_length=256, verbose_name='User`s question'),
        ),
        migrations.AlterField(
            model_name='language',
            name='question_created',
            field=models.CharField(blank=True, max_length=256, verbose_name='Question was succesfully created'),
        ),
        migrations.AlterField(
            model_name='language',
            name='question_menu',
            field=models.CharField(blank=True, max_length=256, verbose_name='"Ask a question" button '),
        ),
        migrations.AlterField(
            model_name='language',
            name='reference_link',
            field=models.CharField(blank=True, max_length=256, verbose_name='Link to the resource'),
        ),
        migrations.AlterField(
            model_name='language',
            name='results',
            field=models.CharField(blank=True, max_length=256, verbose_name='Results of poll'),
        ),
        migrations.AlterField(
            model_name='language',
            name='select_poll',
            field=models.CharField(blank=True, max_length=256, verbose_name='Select poll'),
        ),
        migrations.AlterField(
            model_name='language',
            name='selected_category',
            field=models.CharField(blank=True, max_length=256, verbose_name='Menu for category'),
        ),
        migrations.AlterField(
            model_name='language',
            name='send_contact',
            field=models.CharField(blank=True, max_length=256, verbose_name='"Send contact" button'),
        ),
        migrations.AlterField(
            model_name='language',
            name='skip',
            field=models.CharField(blank=True, max_length=256, verbose_name='"Skip" button'),
        ),
        migrations.AlterField(
            model_name='language',
            name='successful_registration',
            field=models.CharField(blank=True, max_length=256, verbose_name='Successful registatration'),
        ),
        migrations.AlterField(
            model_name='language',
            name='suggestion',
            field=models.CharField(blank=True, max_length=256, verbose_name='"Add suggestion" button'),
        ),
        migrations.AlterField(
            model_name='language',
            name='thanks_suggestion',
            field=models.CharField(blank=True, max_length=256, verbose_name='Thanks for suggestion!'),
        ),
        migrations.AlterField(
            model_name='language',
            name='video',
            field=models.CharField(blank=True, max_length=256, verbose_name='Video-instruction'),
        ),
        migrations.AlterField(
            model_name='language',
            name='video_text',
            field=models.CharField(blank=True, max_length=256, verbose_name='Here is the link to the video'),
        ),
        migrations.AlterField(
            model_name='language',
            name='weight',
            field=models.CharField(blank=True, max_length=256, verbose_name='User`s weight'),
        ),
        migrations.AlterField(
            model_name='language',
            name='write_suggestion',
            field=models.CharField(blank=True, max_length=256, verbose_name='Write your suggestion'),
        ),
        migrations.AlterField(
            model_name='language',
            name='yes',
            field=models.CharField(blank=True, max_length=256, verbose_name='Yes'),
        ),
    ]
