# Generated by Django 4.0.1 on 2022-01-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0062_alter_language_age_alter_language_anonymous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='female',
            field=models.CharField(blank=True, max_length=256, verbose_name='Female'),
        ),
        migrations.AddField(
            model_name='language',
            name='male',
            field=models.CharField(blank=True, max_length=256, verbose_name='Male'),
        ),
        migrations.AddField(
            model_name='question',
            name='user_age',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='User`s age'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='user_gender',
            field=models.CharField(blank=True, max_length=256, verbose_name='User`s gender'),
        ),
        migrations.AddField(
            model_name='question',
            name='user_height',
            field=models.CharField(blank=True, max_length=256, verbose_name='User`s height'),
        ),
        migrations.AddField(
            model_name='question',
            name='user_mariage',
            field=models.CharField(blank=True, max_length=256, verbose_name='User`s marriage status'),
        ),
        migrations.AddField(
            model_name='question',
            name='user_weight',
            field=models.CharField(blank=True, max_length=256, verbose_name='User`s weight'),
        ),
    ]
