# Generated by Django 4.0.1 on 2022-01-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0064_alter_question_user_age_alter_question_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='User`s age'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='User`s gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='User`s height'),
        ),
        migrations.AddField(
            model_name='user',
            name='marriage',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='User`s marriage status'),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='User`s weight'),
        ),
    ]
