# Generated by Django 4.0.1 on 2022-01-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0065_user_age_user_gender_user_height_user_mariage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='incorrect_age',
            field=models.CharField(blank=True, max_length=256, verbose_name='Age is incorrect'),
        ),
    ]
