# Generated by Django 4.0.1 on 2022-01-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0067_rename_incorrect_age_language_incorrect_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='incorrect_data',
            field=models.CharField(blank=True, max_length=256, verbose_name='Input is incorrect'),
        ),
    ]
