# Generated by Django 4.0.1 on 2022-01-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0069_questionnaire_number_answers_user_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='no',
        ),
        migrations.RemoveField(
            model_name='language',
            name='yes',
        ),
        migrations.AddField(
            model_name='language',
            name='no_q',
            field=models.CharField(blank=True, max_length=256, verbose_name='No, enter again'),
        ),
        migrations.AddField(
            model_name='language',
            name='yes_q',
            field=models.CharField(blank=True, max_length=256, verbose_name='Yes in questions'),
        ),
    ]
