# Generated by Django 4.0.1 on 2022-01-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0071_language_no_language_yes'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='final_score',
            field=models.CharField(blank=True, max_length=256, verbose_name='User`s score for poll'),
        ),
    ]
