# Generated by Django 4.0.1 on 2022-01-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0072_language_final_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='marriage',
            new_name='mariage',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='number_answers',
        ),
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='Image for publication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_amount',
            field=models.IntegerField(default=5, verbose_name='Amount of questions'),
        ),
        migrations.AddField(
            model_name='user',
            name='number_answers',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Number of question'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='text',
            field=models.TextField(blank=True, verbose_name='Publication`s text'),
        ),
    ]
