# Generated by Django 4.0.1 on 2022-01-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0072_language_final_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='question_amount',
            field=models.IntegerField(default=5, verbose_name='Amount of questions'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='number_answers',
            field=models.PositiveIntegerField(blank=True, verbose_name='Number of question'),
        ),
    ]
