# Generated by Django 4.0.1 on 2022-01-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0072_language_final_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='marriage',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='number_answers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='marriage',
        ),
        migrations.AddField(
            model_name='language',
            name='mariage',
            field=models.CharField(blank=True, max_length=256, verbose_name='Is user married?'),
        ),
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='Image for publication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_amount',
            field=models.IntegerField(default=5, verbose_name='Amount of questions'),
        ),
        migrations.AddField(
            model_name='user',
            name='mariage',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='User`s marriage status'),
        ),
        migrations.AddField(
            model_name='user',
            name='number_answers',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Number of question'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='text',
            field=models.TextField(blank=True, verbose_name='Publication`s text'),
        ),
    ]
