# Generated by Django 4.0.1 on 2022-01-29 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0073_publication_image_questionnaire_questions_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='number_answers',
        ),
    ]
