# Generated by Django 4.0.1 on 2022-01-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0073_remove_language_marriage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='marriage',
        ),
        migrations.AddField(
            model_name='language',
            name='mariage',
            field=models.CharField(blank=True, max_length=256, verbose_name='Is user married?'),
        ),
    ]
