# Generated by Django 4.0.1 on 2022-01-22 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0073_questionnaire_question_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='marriage',
            new_name='mariage',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='marriage',
            new_name='mariage',
        ),
    ]
