# Generated by Django 4.0.1 on 2022-01-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0074_rename_marriage_language_mariage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='number_answers',
        ),
        migrations.AddField(
            model_name='user',
            name='number_answers',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Number of question'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='text',
            field=models.TextField(blank=True, verbose_name='Publication`s text'),
        ),
    ]
