# Generated by Django 4.0.1 on 2022-01-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0074_remove_language_marriage_language_mariage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='marriage',
        ),
    ]
