# Generated by Django 4.0.1 on 2022-01-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0077_remove_language_marriage_user_number_answers'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='language',
        #     name='marriage',
        #     field=models.CharField(blank=True, max_length=256, verbose_name='Is user married?'),
        # ),
        migrations.AddField(
            model_name='user',
            name='number_answers',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Number of question'),
        ),
    ]
