# Generated by Django 4.0.1 on 2022-01-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0078_language_marriage_user_number_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='marriage',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='User`s marriage status'),
        ),
    ]
